name: GatedBuildTest

on:
  pull_request:
    branches:
      - main

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  RepositoryUrl: 'https://github.com/${{ github.repository }}'
  RepositoryBranch: '${{ github.ref }}'
  SourceRevisionId: '${{ github.sha }}'
  Configuration: Release
  SolutionPath: ProtoAttributor.sln
  Version: '1.4.${{ github.run_number }}'
jobs:
  build-extension:
    uses: d1820/proto-attributor/.github/workflows/dependabot-automerge.yml@SHA
