name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env: 
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  RepositoryUrl: 'https://github.com/${{ github.repository }}'
  RepositoryBranch: '${{ github.ref }}'
  SourceRevisionId: '${{ github.sha }}'
  Configuration: Release
  Version: '1.4.${{ github.run_number }}'
  SolutionPath: ProtoAttributor.sln    
jobs:
  build-extension:
    runs-on: windows-latest
    strategy:
      matrix:
        VsTargetVersion: ['VS2019', 'VS2022']
    env: 
        VsixManifestPath: src\Manifests\${{ matrix.VsTargetVersion }}\source.extension.vsixmanifest
        VsTargetVersion: '${{ matrix.VsTargetVersion }}'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2   
    - name: Setup .NET Core 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'   
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore NuGet Packages
      run: nuget restore $env:SolutionPath
    - name: Build extension
      run: msbuild $env:SolutionPath /t:Rebuild
      env: 
        DeployExtension: False
    - name: Test extension
      run: dotnet test --no-build --verbosity normal $env:SolutionPath

